version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: xyz_retail_db
    environment:
      POSTGRES_DB: xyz_retail
      POSTGRES_USER: not_root_user
      POSTGRES_PASSWORD: top_secret_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: xyz_retail_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/xyz_retail
      SPRING_DATASOURCE_USERNAME: not_root_user
      SPRING_DATASOURCE_PASSWORD: top_secret_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xyz-retail-frontend
    ports:
      - "5000:80"
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: