spring.application.name=xyz_retail
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/xyz_retail
spring.datasource.username=not_root_user
spring.datasource.password=top_secret_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Disable spring session
spring.session.store-type=none
#sendgrid.api-key=${SENDGRID_API_KEY:Null}
sendgrid.api-key=null
app.email.from=irfan.selcuk.bilir@gmail.com
app.email.template.order-confirmation=d-56b75f79348b445da5aa5a53b71a7a24
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
resilience4j.retry.instances.sendgrid.max-attempts=3
resilience4j.retry.instances.sendgrid.wait-duration=1s
resilience4j.retry.instances.sendgrid.enable-exponential-backoff=true
resilience4j.retry.instances.sendgrid.exponential-backoff-multiplier=2
resilience4j.circuitbreaker.instances.sendgrid.sliding-window-size=10
resilience4j.circuitbreaker.instances.sendgrid.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.sendgrid.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.sendgrid.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.sendgrid.permitted-number-of-calls-in-half-open-state=3

server.port=8090